NODE_ENV=development
PORT=3000
HOST=http://localhost:3000

NODE_ENV=development
PORT=3000

API_URL=localhost:3000

DB_PORT=5432
DB_HOST=localhost
DB_DATABASE=__DB_DATABASE__
DB_USERNAME=__DB_USERNAME__
DB_PASSWORD=__DB_PASSWORD__

AUTH_TOKEN_SECRET=secret

REDIS_HOST=localhost
REDIS_PORT=6379

CLIENT_URL=http://localhost:4200
